admin/src/web/controllers/socios.py
from flask import render_template, Blueprint, flash, request, redirect, url_for, session
from sqlalchemy import asc, desc
from src.web.helpers import pagination 
from src.core import auth
from src.core import business
from src.core import config
from src.core import image
from src.web.controllers.forms import RegisterSocioForm
from src.core.auth import assign_disciplinas, get_socio_id
from src.web.helpers.choices_loader import load_disciplinas
from src.web.helpers.choices_loader import load_genders
from src.web.helpers.choices_loader import load_type_id 
from src.web.helpers.roles import permission_required
from src.web.helpers.auth import login_required
from src.web.helpers.formatters import socio_format
from src.web.helpers.formatters import generar_info_carnet
from src.web.controllers import exporter
from src.web.helpers.adaptators import generate_qr
from src.web.helpers.adaptators import image_resize
import base64


socio_blueprint = Blueprint("socio", __name__, url_prefix="/socio")


# List Socio
@socio_blueprint.route("/index/", methods=["GET", "POST"])
@login_required
@permission_required(perm="socio_index")
def index_socios():
    '''Manejador de vista que muestra un listado con todos los socios, permitiendo realizar
    búsquedas por distintos criterios'''
    
    session['accion'] = 'Index'
    socios = auth.get_all_socios()
    exists = socios.count() > 0
    socios = auth.socios_format(socios)

    order = True if config.get_configuration().criterio == "asc" else False
    if order:
        socios = socios.order_by(asc("apellido"), desc("estado"))
    else:
        socios = socios.order_by(desc("apellido"), desc("estado"))
    pages = socios.paginate(page=pagination.pagination(), per_page=config.ELEM_PER_PAGE())
    
    return render_template("socios/index.html", socios=socios, pages=pages, exists=exists)

# Create Socio
@socio_blueprint.route("/create", methods=["GET", "POST"])
@login_required
@permission_required(perm="socio_new")
def create_socio():
    form = RegisterSocioForm()
    form.disciplines.choices = load_disciplinas()
    form.gender.choices = load_genders()
    form.type_ID.choices = load_type_id()
    if form.validate_on_submit():
        socio = auth.load_socio(nombre=form.name.data.capitalize(),
                        apellido=form.lastname.data.capitalize(),
                        tipo_identificacion=form.type_ID.data,
                        identificacion=form.value_ID.data,
                        email=form.email.data,
                        genero=form.gender.data,
                        telefono="" if not form.phone.data else form.phone.data,
                        domicilio=form.address.data,
                        estado_act_block=True)
        if(form.disciplines.data is not None):
            added = []
            for disciplina in form.disciplines.data:
                next = business.get_disciplina(disciplina)
                added.append(next)
            assign_disciplinas(socio, added)
                
        flash("Se ha cargado el socio con éxito", "success")
        return redirect(url_for("socio.create_socio"))
        
    return render_template("socios/alta_socio.html", form=form)

# Update Socios
@socio_blueprint.route("/edit/<int:id>", methods=["GET", "POST"])
@login_required
@permission_required(perm="socio_update")
def edit_socio(id):
    session["socio_edit"] = id
    socio_to_update = auth.get_socio_id(id)
    form = RegisterSocioForm(obj=socio_to_update)
    form.disciplines.choices = load_disciplinas()
    form.gender.choices = load_genders()
    form.type_ID.choices = load_type_id()
    if form.validate_on_submit():
        # Socio new data
        socio_to_update.nombre = request.form['name'].capitalize()
        socio_to_update.apellido = request.form['lastname'].capitalize()
        socio_to_update.tipo_identificacion = request.form['type_ID']
        socio_to_update.identificacion = request.form['value_ID']
        socio_to_update.email = request.form['email']
        socio_to_update.genero = request.form['gender']
        socio_to_update.telefono = request.form['phone']
        socio_to_update.domicilio = request.form['address']
        nuevo_estado = request.form.get('estado')
        if nuevo_estado is not None:
            socio_to_update.estado_act_block = True if nuevo_estado == 'True' else False
        else:
            socio_to_update.estado_act_block = socio_to_update.estado_act_block
        if(form.disciplines.data is not None):
            added = []
            for disciplina in form.disciplines.data:
                next = business.get_disciplina(disciplina)
                added.append(next)
            assign_disciplinas(socio_to_update, added)
        
        del session["socio_edit"]
        # Update socio in db
        try:
            auth.update_socio(socio_to_update)
            message = "Socio {} {} actualizado".format(socio_to_update.nombre, socio_to_update.apellido)
            flash(message, "success")
            return redirect(url_for("socio.index_socios"))
        except:
            flash("Error, intente de vuelta", "error")
            return render_template("socios/editar_socio.html", form=form, socio_to_update=socio_to_update)
    del session["socio_edit"]

    return render_template("socios/editar_socio.html", form=form, socio_to_update=socio_to_update)

@socio_blueprint.get("/edit/<int:id>/switch_estado")
@login_required
@permission_required(perm="socio_switch_state")
def switch_estado(id):
    socio_to_switch = auth.get_socio_id(id)

    if socio_to_switch.estado_act_block:
        socio_to_switch.estado_act_block = False
    else:
        socio_to_switch.estado_act_block = True
    
    try:
        auth.update_socio(socio_to_switch)
        message = "Estado de socio {} {} actualizado".format(socio_to_switch.nombre, socio_to_switch.apellido)
        flash(message, "success")
        return redirect(url_for("socio.index_socios"))
    except:
        flash("Error, intente de vuelta", "error")
        return render_template("socios/index_socios.html")


# Delete Socio
@socio_blueprint.route("/delete/<int:id>")
@login_required
@permission_required(perm="socio_destroy")
def delete_socio(id):
    socio_to_delete = auth.get_socio_id(id)
    try:
        auth.delete_socio(id)
        message = "Socio {} eliminado".format(socio_to_delete.apellido)
        flash(message, "success")
        return redirect(url_for("socio.index_socios"))
    except:
        flash("Error, intente de vuelta", "error")
        return redirect(url_for("socio.index_socios"))

# Search Socio
@socio_blueprint.route("/index/search", methods=["GET", "POST"])
@login_required
@permission_required(perm="socio_show")
def search():
    session['accion'] = 'Search'
    session['estado'] = request.form.get('estado')
    session['searched'] = request.form.get('searched')

    return redirect(url_for('socio.search_results'))


@socio_blueprint.get("/index/search_results")
@login_required
@permission_required(perm="socio_show")
def search_results():
    '''Muestra los resultados de búsqueda del listado de socios'''
    
    searched = session['searched']
    estado = session['estado']
    if not searched and estado == 'todos':
        flash("Ingrese o seleccione un criterio para realizar una búsqueda", "info")
        return redirect(url_for("socio.index_socios"))

    socios = auth.get_all_socios(estado, searched)

    if(socios.count() == 0):
        flash("No se ha encontrado ningún socio con el criterio ingresado", "error")
        return redirect(url_for('socio.index_socios'))
    
    order = True if config.get_configuration().criterio == "asc" else False
    if order:
        socios = socios.order_by(asc("apellido"), desc("estado"))
    else:
        socios = socios.order_by(desc("apellido"), desc("estado"))
    pages = socios.paginate(page=pagination.pagination(), per_page=config.ELEM_PER_PAGE())
    return render_template("socios/search.html", pages=pages, exists=True,  s=estado, n=searched, added="search_results")

# Socio information
@socio_blueprint.get("/info/<id>")
@login_required
@permission_required(perm="socio_show")
def show_info(id):
    '''Muestra la información detallada de un socio en particular.'''
    
    socio = get_socio_id(id)
    socio_format(socio)

    return render_template("socios/informacion.html", socio=socio)


# Export list
@socio_blueprint.get("/download/<opc>")
@login_required
@permission_required(perm="socio_index")
def download(opc):
    if session['accion'] == 'Index':
        socio_list = auth.get_all_socios()
    elif session['accion'] == 'Search':
        socio_list = auth.get_all_socios(session['estado'], session['searched'])
    
    if opc == 'PDF':
        return exporter.pdf_report(socio_list)
    elif opc == 'CSV':
        return exporter.csv_report(socio_list)
    

# Socio's Carnet
@socio_blueprint.route('/upload/<socio_id>', methods=['GET', 'POST'])
@login_required
@permission_required(perm="socio_show")
def upload(socio_id):

    socio = get_socio_id(socio_id)
    socio_format(socio)

    if request.method == 'POST':
        # Image
        file = request.files['file']
        if file.filename.split('.')[1] not in ['jpg', 'png']:
            flash("Sólo se permiten archivos jpg o png", "error")
            return redirect(url_for('socio.index_socios'))
        
        # Resize and encode Image
        image_64 = base64.b64encode(image_resize(file))
        mimetype = '.' + file.filename.split('.')[1]
        upload = image.load_image(filename=file.filename, data=image_64,
                                        mimetype=mimetype, socio_id=socio.id)

        message = "Carnet de socio {} creado".format(socio.id)
        flash(message, "success")
        return redirect(url_for('socio.show', socio_id=socio.id))

    return render_template('socios/upload_carnet.html', socio=socio)

@socio_blueprint.route('/<socio_id>/carnet', methods=['GET', 'POST'])
@login_required

admin/src/web/templates/socios/alta_socio.html
{% extends "base.html" %}
{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/form_alta.css') }}">
{% endblock %}
{% from "macros.html" import check_errors %}

{% if has_permission("socio_new") %}
    {% set active_page = "socios" %}
    {% block title %} 
        Registrar un nuevo socio
    {% endblock %}


    {% block content %}
        <div class="container py-5 form_width">
            <h1 class="text-center fw-semibold mb-4">Cargar socio</h1>
            <form name="registerForm needs-validation" method="POST">
                {{ form.csrf_token }}
                
                <div class="form-group">
                    <div class="mb-2">
                        <div class="d-grid gap-2 gap-md-4 d-md-flex justify-content-md-center">
                            <div class="col">
                                <label for="name" class="form-label">{{ form.name.label }}</label>
                                {{ form.name(class_="form-control", size=32) }}
                                {{ check_errors(form.name) }} 
                            </div>
                            <div class="col">
                                <label for="lastname" class="form-label">{{ form.lastname.label }}</label>
                                {{ form.lastname(class_="form-control", size=32) }}
                                {{ check_errors(form.lastname) }} 
                            </div>
                        </div>  
                    </div>
                    <div class="mb-2">
                        <label for="email" class="form-label">{{ form.email.label }}</label>
                        {{ form.email(class_="form-control", size=32) }}
                        {{ check_errors(form.email) }}
                    </div>
                    <div class="mb-2">
                        <div class="rd-grid gap-4 d-md-flex justify-content-md-center mt-auto mb-2">
                            <div class="col">
                                <label for="identificación" class="form-label">{{ form.type_ID.label }}</label>
                                {{ form.type_ID(class="form-control") }}
                                {{ check_errors(form.type_ID) }}
                            </div>
                            <div class="col mt-2 mt-md-0">
                                <label for="identificación" class="form-label">{{ form.value_ID.label }}</label>
                                {{ form.value_ID(class_="form-control", size=32) }}
                                {{ check_errors(form.value_ID) }}
                            </div>
                        </div>
                    </div>
                    <div class="mb-2">
                        <label for="genero" class="form-label">{{ form.gender.label }}</label>
                        {{ form.gender(class="form-control") }}
                        {{ check_errors(form.gender) }}
                    </div>
                    <div class="mb-2">
                        <div class="rd-grid gap-4 d-md-flex justify-content-md-center mt-auto mb-2">
                            <div class="col">
                                <label for="telefono" class="form-label">{{ form.phone.label }}</label>
                                {{ form.phone(class_="form-control", size=32) }}
                                {{ check_errors(form.phone) }}
                            </div>
                            <div class="col mt-2 mt-md-0">
                                <label for="domicilio" class="form-label">{{ form.address.label }}</label>
                                {{ form.address(class_="form-control", size=32) }}
                                {{ check_errors(form.address) }}
                            </div>
                        </div>
                    </div>
                    <div class="mb-3">
                        <label for="disciplinas" class="form-label">{{ form.disciplines.label }}</label>
                        {{ form.disciplines(class="form-control") }}
                        {{ check_errors(form.disciplines) }}
                    </div>
                </div>
                <div class="d-grid gap-2 d-md-flex justify-content-md-center mt-auto py-4">
                    <button type="submit" class="btn btn-dark">Registrar socio</button>
                    <a class="btn btn-dark" href="{{ url_for('socio.index_socios') }}">Cancelar</a>
                </div>
            </form>
        </div>
    {% endblock %}
{% endif %}

admin/src/web/templates/socios/index.html
{% extends "base.html" %}
{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/index.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/modal.css') }}">
    <style>
        @media only screen and (max-width: 767px),
        (min-device-width: 768px) and (max-device-width: 995px)  {
                /*
            Label the data
            */
            td:nth-of-type(1):before { content: "Nro de socio"; }
            td:nth-of-type(2):before { content: "Nombre"; }
            td:nth-of-type(3):before { content: "Tipo de documento"; }
            td:nth-of-type(4):before { content: "Documento"; }
            td:nth-of-type(5):before { content: "Estado"; }
            td:nth-of-type(6):before { content: "Estado pagos"; }
            td:nth-of-type(7):before { content: "Pagos"; }
            td:nth-of-type(8):before { content: "Opciones"; }
            td:nth-of-type(9):before { content: "Usuario"; }
        }

        #mHeader{
            padding-bottom: 70px;
        }
    </style>
{% endblock %}

{% if has_permission("socio_index") %}

    {% set active_page = "socios" %}

    {% block title %}Listado de socios{% endblock %}

    {% block content %}
        <div class="container py-5 justify-content-center"> 
            {% block header_title %}
                <h1 class="text-center fw-semibold mb-4">Listado de socios</h1>
            {% endblock %}
            
            {% if has_permission("socio_show") %}
                <form method="POST" action="{{ url_for('socio.search') }}">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                    <div class="d-grid gap-2 gap-md-4 d-md-flex justify-content-md-center py-2">
                        <div class="dropdown">
                            <select class="form-select" id="select" name="estado">
                                <option value="todos" {% if s=="todos" %} selected="selected"{% endif %}>Todos</option>
                                <option value="False" {% if s=="False" %} selected="selected"{% endif %}>Activos</option>
                                <option value="True" {% if s=="True" %} selected="selected"{% endif %}>Inactivos</option>
                            </select>
                        </div>
                        <!--Buscar socio-->
                        <div class="col">
                            <div class="input-group mb-3">
                                <input class="form-control" type="text" placeholder="López" name="searched" {% if n %} value="{{n}}" {% endif %}>
                                <button type="submit" class="btn btn-dark">Buscar</button>
                            </div>
                        </div>
                    </div>
                </form>
            {% endif %}
            {% if exists %}
                <div class="table table-dark">
                    <table id="socios_table" data-toggle="table">
                        <thead>
                            <tr>
                                <th># Socio</th>
                                <th>Nombre</th>
                                <th>Tipo</th> 
                                <th>Documento</th>
                                <th>Estado</th>
                                <th>Estado pagos</th>
                                <th>Pagos</th>
                                <th>Opciones</th>
                                {% if has_permission("socio_destroy") %}<th>Usuario</th>{% endif %}
                            </tr>
                        </thead>
                        <tbody>
                            {% for socio in pages.items %} 
                                <tr>
                                    <td>{{ socio.id }}</td>
                                    <td>{{socio.nombre}} {{socio.apellido}}</td>
                                    <td>{{socio.tipo_identificacion}}</td>
                                    <td>{{socio.identificacion}}</td>
                                    <td>{% if socio.estado_act_block %}<span class="badge text-bg-success">Activo</span>{% else %}<span class="badge text-bg-danger">Bloqueado</span>{% endif %}</td> <!--Estado de socio-->
                                    <td>{% if socio.estado == "Impaga" %}
                                            <a class="btn btn-borrar btn-sm btn-floating rounded-circle">
                                            <i class="bi bi-x"></i></a>
                                        {% else %}
                                            <a class="btn btn-success btn-sm btn-floating rounded-circle">
                                            <i class="bi bi-check"></i></a>
                                        {% endif %}</td> <!--Estado de pagos de socio-->
                                    <td>
                                        <!--Ver cuotas-->
                                        <a href="{{ url_for('pagos.cuotas_socio', id = socio.id) }}">
                                            <button type="button" class="btn btn-sm btn-outline-info">Cuotas</button>
                                        </a>
                                    </td>
                                    <td>
                                    <div class="d-grid gap-2 d-md-flex justify-content-lg-center justify-content-start mt-auto">
                                        {% if has_permission("socio_show") %}
                                            <!--Más info-->
                                            <a href="{{ url_for('socio.show_info', id = socio.id) }}">
                                                <button type="button" class="btn btn-sm btn-inscribir">Más info</button>
                                            </a>
                                        {% endif %}
                                        {% if has_permission("socio_update") %}
                                            <!--Editar socio-->
                                            <a href="{{ url_for('socio.edit_socio', id = socio.id) }}">
                                                <button type="button" class="btn btn-sm btn-especial">Editar</button>
                                            </a>
                                        {% endif %}
                                        {% if has_permission("socio_destroy") %}
                                            <!-- Button trigger modal for deletion -->
                                            <button type="button" class="btn btn-sm btn-borrar" data-bs-toggle="modal" data-bs-target="#staticBackdrop-{{socio.id}}">
                                                Eliminar
                                            </buttoni>
                                        {% endif %}
                                    </div>

                                        
                                    <!-- Modal -->
                                    <div class="modal fade" id="staticBackdrop-{{socio.id}}" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                <h1 class="modal-title fs-5">Confirmación de eliminación</h1>
                                                </div>
                                                <div class="modal-body">
                                                    <p>¿Está segur@ que desea eliminar al socio?</p>
                                                </div>
                                            
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                                                    <a href="{{ url_for('socio.delete_socio', id = socio.id) }}"> <!--AGREGAR DESTROY PARA SOCIO-->
                                                        <button type="button" class="btn btn-borrar">Eliminar</button>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                                {% if has_permission("socio_destroy") %}
                                    <td>
                                        {% if not socio.username %}
                                            <!--Dar usuario de socio de alta-->
                                            <a href="{{ url_for('socio.socios_user', id = socio.id) }}">
                                                <button type="button" class="btn btn-sm btn-outline-especial">Crear</button>
                                            </a>
                                        {% else %}
                                        <a class="btn btn-outline-especial btn-sm btn-floating rounded-circle"><i class="bi bi-check"></i></a>
                                        {% endif %}
                                    </td>
                                {% endif %}
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% else %}
                <h1>NO EXISTEN SOCIOS CARGADOS</h1>
            {% endif %}
        </div>
        {% endblock %}
        {% block buttons %}
            <div class="d-grid gap-4 d-md-flex align-items-center justify-content-md-between mt-auto pt-4 pb-2">
                <!--Paginación-->
                {% include "paginacion.html" %}
                <div class="justify-content-md-end">
                    {% if has_permission("socio_new") %}
                        <!--Agregar socio-->
                        <a href="{{ url_for('socio.create_socio') }}" class="btn btn-dark">Agregar socio</a>
                    {% endif %}
                    <!--Exportar listado-->
                    <div class="dropdown">
                        <button class="btn btn-secondary btn-dark dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Exportar
                        </button>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{{ url_for('socio.download', opc='PDF') }}">PDF</a></li>
                            <li><a class="dropdown-item" href="{{ url_for('socio.download', opc='CSV') }}">CSV</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            {% block button_bottom %}{% endblock %}
        {% endblock %}
{% endif %}

admin/src/web/templates/socios/informacion.html
{% extends "base.html" %}
{% block head %}
    {{super()}}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/informacion_cuota.css') }}">
{% endblock %}

{% if has_permission("socio_show") %}
    {% set active_page = "socios" %}
    {% block title %}Información del socio{% endblock %}

    {% block content %}
        <div class="container-fluid py-5 text-center">
            <h1 class="text-center fw-semibold mb-5">Información del socio</h1>
            <div class="col d-flex justify-content-center">
                <div class="card mb-3">
                    <h5 class="card-header text-center fw-semibold">
                        Número de socio: #{{socio.id}}
                    </h5>
                    <div class="card-body">
                        <p class="card-text">Nombre: {{socio.nombre}}</p>
                        <p class="card-text">{{socio.tipo_identificacion}}: {{socio.identificacion}}</p>
                        {% if socio.email|length %}
                            <p class="card-text">Email: {{socio.email}}</p>
                        {% endif %}
                        {% if socio.username %}
                            <p class="card-text">Nombre de usuario: {{socio.username}}</p>
                        {% endif %}
                        <p class="card-text">Género: {{socio.genero}}</p>
                        <p class="card-text">Teléfono: {% if socio.telefono|length %}{{socio.telefono}}{% else %}no cargado{% endif %}</p>
                        <p class="card-text">Domicilio: {{socio.domicilio}}</p>
                        {% if socio.disciplinas|length %}
                            <p class="card-text">Disciplinas:</p>
                            <ul class="list-group">
                            {% for disciplina in socio.disciplinas %} 
                                <li class="list-group-item">{{disciplina.nombre_disciplina}}</li>
                            {% endfor %}
                            </ul>
                        {% endif %}
                        <hr>
                        <p class="card-text">Estado: {% if socio.estado %}Inactivo{% else %}Activo{% endif %}</p>
                        {% if has_permission("payments_show") %}
                            <div class="my-2">
                                <a href="{{ url_for('pagos.cuotas_socio', id = socio.id) }}">
                                    <button type="button" class="btn btn-inscribir">Cuotas</button>
                                </a>
                                {% if socio.image %}
                                    <a class="btn btn-dark" href="{{ url_for('socio.show', socio_id=socio.id) }}">Ver carnet</a>
                                {% else %}
                                    <a class="btn btn-dark" href="{{ url_for('socio.upload', socio_id=socio.id) }}">Generar carnet</a>
                                {% endif %}
                            </div>
                        {% endif %}
                        <div class="card-footer text-muted">Fecha de creación: {{socio.fecha_alta|datetime_format('%d-%m-%Y')}}</div>
                    </div>
                </div>
            </div>
            <a class="btn btn-dark" href="{{ url_for('socio.index_socios') }}">Volver al listado de socios</a>
        </div>
    {% endblock %}
{% endif %}

admin/src/web/templates/socios/search.html
{% extends "socios/index.html" %}
{% if has_permission("socio_show") %}
    {% block title %}Resultados de búsqueda{% endblock %}
    {% block header_title %}
        <h1 class="text-center fw-semibold mb-4">Resultado de búsqueda</h1>
    {% endblock %}
    {% block button_bottom %}
        <div class="d-grid gap-2 d-md-flex justify-content-md-center mt-auto pt-2">
            <a href="{{ url_for('socio.index_socios') }}" class="btn btn-dark">Retornar a listado general</a>
            </a>
        </div>
    {% endblock %}
{% endif %}

admin/src/web/templates/socios/upload_carnet.html
{% extends "base.html" %}
{% block head %}
    {{super()}}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/informacion_cuota.css') }}">
{% endblock %}

{% set active_page = "socios" %}
{% block title %}Información del socio{% endblock %}

{% block content %}
    <div class="container-fluid py-5 text-center">
        <h1 class="text-center fw-semibold mb-5">Creación de carnet</h1>
        <div class="col d-flex justify-content-center">
            <div class="card mb-3">
                <h5 class="card-header text-center fw-semibold">
                    Número de socio: #{{socio.id}}
                </h5>
                <div class="card-body">
                    <p class="card-text">Por favor, ingrese imagen de perfil del socio</p>
                    <div class="center">
                        <form method="POST" action="{{ url_for('socio.upload', socio_id=socio.id) }}" enctype="multipart/form-data">
                            <div class="input-group mb-3">
                                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                                <input type="file" name="file" class="form-control" required>
                                <button class="btn btn-dark">Subir</button>
                            </div>
                        </form>
                        
                    </div>
                </div>
            </div>
        </div>
        <a class="btn btn-dark" href="{{ url_for('socio.index_socios') }}">Volver al listado de socios</a>
    </div>
{% endblock %}