admin/src/web/controllers/admin.py
from flask import render_template, Blueprint, flash, redirect, url_for, session, request
from src.web.helpers.choices_loader import load_roles_without_admin
from src.core import auth, roles
from src.web.controllers.forms import EditProfileByAdminForm
from src.core import config
from src.web.helpers.choices_loader import load_tabla_pagos, load_criterio
from src.web.helpers.auth import login_required
from src.web.helpers.roles import permission_required
from src.web.controllers.forms import ConfigForm

admin_blueprint = Blueprint("admin", __name__, url_prefix="/admin")

@admin_blueprint.route("/config", methods=["GET", "POST"])
@login_required
@permission_required(perm="config")
def configuration():
    act_config = config.get_configuration()
    form = ConfigForm(criterio=act_config.criterio)
    form.cant.default = act_config.cant_elem
    form.cant_pagos_permitidos.default = act_config.cant_pagos_permitidos
    form.criterio.choices = load_criterio()
    form.pagos.choices = load_tabla_pagos()
    if form.validate_on_submit():
        act_config.cant_elem = form.cant.data
        act_config.criterio = form.criterio.data
        act_config.pagos = form.pagos.data
        act_config.cant_pagos_permitidos = form.cant_pagos_permitidos.data
        act_config.email = form.email.data
        act_config.phone = form.phone.data
        act_config.recibo_txt = form.recibo_txt.data if form.recibo_txt.data is not None else ""
        act_config.cuota_base = form.cuota_base.data
        act_config.recargo = form.recargo.data

        config.update_configuration(act_config)
        flash("Configuración actualizada", "success")
        return redirect(url_for("user.index_users"))
    return render_template("admin/config.html", form=form, config=act_config)

@admin_blueprint.route("/profile", methods=["GET", "POST"])
@login_required
@permission_required(perm="profile")
def profile():
    admin_username = session.get("username")
    admin_edit = auth.get_user_by_username(admin_username)
    form = EditProfileByAdminForm(obj=admin_edit)
    
    # Datos que NO se pueden modificar
    form.roles.choices = load_roles_without_admin()

    # Datos que sí se pueden modificar
    if form.validate_on_submit():
        admin_edit.nombre = (form.name.data).capitalize()
        admin_edit.apellido = request.form['lastname'].capitalize()
        admin_edit.email = request.form['email']
        if(form.roles.data is not None):
            added = []
            for nombre_rol in form.roles.data:
                next = roles.get_rol_by_name(nombre_rol)
                added.append(next)
            roles.assign_roles(admin_edit, added)
        
        # Update user in db
        try:
            auth.update_user(admin_edit)
            message = "Usuario {} actualizado".format(admin_edit.username)
            flash(message, "success")
            return render_template("admin/profile.html", form=form, admin=admin_edit)
        except:
            flash("Error, intente de vuelta", "error")
            return render_template("admin/profile.html", form=form, admin=admin_edit)

    return render_template("admin/profile.html", form=form, admin=admin_edit)

admin/src/web/controllers/auth.py
from flask import Blueprint
from flask import request
from flask import redirect
from flask import url_for
from flask import flash
from flask import session
from src.core import auth
from src.web.helpers.auth import login_required

auth_blueprint = Blueprint("auth", __name__, url_prefix="/auth")

@auth_blueprint.post("/authenticate") 
def authenticate():
    '''Autentica los datos de sesión ingresados.
    En caso de ser incorrectos, se retorna un mensaje de error.
    En caso de ser correctos, se loguea al usuario y se muestra un mensaje de error.'''

    user = auth.find_user_by_username_and_pass(request.form["username"], request.form["password"])
    if not user:
        flash("Username o clave incorrecta.", "error")
        return redirect(url_for("landing"))

    if not user.estado:
        flash("Cuenta bloqueada", "error")
        return redirect(url_for("landing"))

    session["username"] = user.username
    flash("La sesión se inició correctamente.", "success")
    
    return redirect(url_for("user.index_users"))


@auth_blueprint.get("/logout")
@login_required
def logout():
    '''Desautentica al usuario.'''

    del session["username"]
    session.clear()

    return redirect(url_for("landing"))

admin/src/web/templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    {% block head %}
    <meta charset="utf-8">
	  <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='images/favicon/apple-touch-icon.png') }}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='images/favicon/favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='images/favicon/favicon-16x16.png') }}">
    <link rel="manifest" href="{{ url_for('static', filename='images/favicon/site.webmanifest') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <title>{% block title %}{% endblock %}</title>
    {% endblock %}
</head>

{% block body %}
<body class="d-flex flex-column min-vh-100"> 
    <header>
        {% block navbar %}
        {% include "navbar.html" %}
        {% endblock %}
    </header>
    <main>
        {% with messages = get_flashed_messages(with_categories=true) %} 
            {% if messages %} 
                {% for category, message in messages %} 
                    <p class="flash {{category}}">{{ message }}</p>
                {% endfor %} 
            {% endif %} 
        {% endwith %}
        {% block content %}
        {% endblock %}
    </main>
    <div class="w-100 mt-auto">
      <div class="container mb-5">
        {% block buttons %} 
        {% endblock %}
      </div>
      <footer class="bg-dark text-center text-white">
          {% block footer %} 
                <!-- Grid container -->
                <div class="container p-4 pb-0">
                  <!-- Section: Social media -->
                  <section class="mb-4">
                    <!-- Facebook -->
                    <a class="btn btn-outline-light btn-floating m-1 rounded-circle" href="https://www.facebook.com/eldepove" target="_blank" role="button"
                      ><i class="bi bi-facebook"></i
                    ></a>
              
                    <!-- Twitter -->
                    <a class="btn btn-outline-light btn-floating m-1 rounded-circle" href="https://twitter.com/deportivove" target="_blank" role="button"
                      ><i class="bi bi-twitter"></i
                    ></a>
              
                    <!-- Instagram -->
                    <a class="btn btn-outline-light btn-floating m-1 rounded-circle" href="https://www.instagram.com/eldepove/" target="_blank" role="button"
                      ><i class="bi bi-instagram"></i
                    ></a>
                  </section>
                  <!-- Section: Social media -->
                </div>
                <!-- Grid container -->
            
                <!-- Copyright -->
                <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
                  Proyecto de software:
                  <a class="text-white" href="https://gitlab.catedras.linti.unlp.edu.ar/proyecto2022/Proyectos/grupo19" target="_blank">Grupo 19</a>
                </div>
                <!-- Copyright -->
          {% endblock %}
      </footer>
    </div>
</body>
{% endblock %}

admin/src/web/templates/error.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/error.css') }}" />
    {% endblock %}
    <title>Error!</title>
  </head>
  <body>
    <h1>{{ error_name }}</h1>
    <p class="zoom-area"><b>Error!</b> {{ error_description }} </p>
      <div class="link-container">
        <a href="{{ url_for('landing') }}" class="more-link">Go to the homepage</a>
      </div>
  </body>
</html>

admin/src/web/templates/land_page.html
{% extends "base.html" %}
{% block head %} 
  {{ super() }}
  <link rel="stylesheet" href="{{ url_for('static', filename='css/land_page.css') }}">
{% endblock %}

{% block navbar %}
{% endblock %}

{% block title %}Bienvenido{% endblock %}
    
{% block body %} 
  <body class="text-center form-signin w-100 m-auto">
    <div class="row">
      <form action="{{ url_for('auth.authenticate')}}" method="POST" class="col-12">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        <img class="mb-4" src="{{ url_for('static', filename='images/logo.png') }}" alt="LOGO DEL CLUB" width="72" height="72">
        <h1 class="h3 mb-3 fw-semibold">Club deportivo Villa Elisa</h1>

        <div class="form-floating">
          <input type="username" name="username" id="floatingInput" class="form-control" placeholder="Nombre de usuario" required>
          <label for="floatingInput">Nombre de usuario</label>
        </div>
        <div class="form-floating">
          <input type="password" name="password" class="form-control" id="floatingPassword" placeholder="Contraseña" required>
          <label for="floatingPassword" >Contraseña</label>
        </div>

        <button class="w-100 btn btn-lg btn-light" type="submit">Iniciar sesión</button>
        <p class="mt-5 mb-3 text-muted">&copy; Proyecto de software - Grupo 19</p>
      </form>
      <div class="mb-4 col-12">
        {% with messages = get_flashed_messages(with_categories=true) %} 
            {% if messages %} 
                {% for category, message in messages %} 
                    <p class="flash {{category}}">{{ message }}</p>
                {% endfor %} 
            {% endif %} 
        {% endwith %}
      </div>
    </div>
  </body>
{% block footer %}

{% endblock %}
{% endblock %}

admin/src/web/templates/macros.html
{% macro check_errors(field) %}
    {% if field.errors %}
        {% for error in field.errors %}
            <div class="text-danger mt-1">{{ error }}</div>
        {% endfor %}
    {% endif %}
{% endmacro %}

admin/src/web/templates/navbar.html
<link rel="stylesheet" href="{{ url_for('static', filename='css/navbar.css') }}">

<nav class="navbar sticky-top navbar-expand-md bg-light" role="navigation">
    <div class="container-fluid">
      <a class="navbar-brand" href="{{url_for('user.index_users')}}">
        <img src="{{url_for('static', filename='images/logo.png')}}" alt="Logo" width="50" height="50" class="d-inline-block align-text-middle">
            Club Deportivo Villa Elisa
      </a>
      <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0 gap-1">
          {% if has_permission("user_index") %}
            <li class="nav-item">
              <a class="nav-link {{ 'active' if active_page == 'users' }}" aria-current="page" href="{{ url_for('user.index_users') }}">Usuarios</a>
            </li>
          {% endif %}
          {% if has_permission("socio_index") %}
            <li class="nav-item">
              <a class="nav-link {{ 'active' if active_page == 'socios' }}" aria-current="page" href="{{ url_for('socio.index_socios') }}">Socios</a>
            </li>
          {% endif %}
          {% if has_permission("payments_index") %}
            <li class="nav-item">
              <a class="nav-link {{ 'active' if active_page == 'disciplinas' }}" aria-current="page" href="{{ url_for('disciplinas.disciplinas_listado' )}}">Disciplinas</a>
            </li>
          {% endif %}
          {% if has_permission("discipline_index") %}
            <li class="nav-item">
              <a class="nav-link {{ 'active' if active_page == 'pagos' }}" aria-current="page" href="{{ url_for('pagos.searcher' )}}">Pagos</a>
            </li>
          {% endif %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="margin-left: 0%;">
              {{session.get("username")}}
            </a>
            <ul class="dropdown-menu dropdown-menu-end">
              {% if has_permission("profile") %}
                <li><a class="dropdown-item" href="{{ url_for('admin.profile') }}">Perfil</a></li>
              {% endif %}
              {% if has_permission("config") %}
                <li><a class="dropdown-item" href="{{ url_for('admin.configuration') }}">Configuración</a></li>
              {% endif %}
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{{ url_for('auth.logout') }}">Cerrar sesión</a></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
</nav>

admin/src/web/templates/paginacion.html
{% block paginacion %}
    <div class="paginacion align-bottom">
        <nav aria-label="...">
            <ul class="pagination flex-wrap"  style="margin-bottom: 0px;">
                <li class="page-item {% if not pages.has_prev %} disabled {% endif %}">
                <a class="full-text page-link" href="./{{added}}?page={{ pages.prev_num }}">Anterior</a>
                <a class="short-text page-link" href="./{{added}}?page={{ pages.prev_num }}">&lt;</a>
                </li>
                {% for page in pages.iter_pages() %}
                    {% if page == pages.page %}
                        <li class="page-item active">
                            <span class="page-link">{{ page }}</span>
                        </li>
                    {% else %}
                        <li class="page-item"><a class="page-link" href="./{{added}}?page={{ page }}">{{ page }}</a></li>
                    {% endif %}
                {% endfor %} 
                <li class="page-item {% if not pages.has_next %} disabled {% endif %}">
                <a class="full-text page-link" href="./{{added}}?page={{ pages.next_num }}">Siguiente</a>
                <a class="short-text page-link" href="./{{added}}?page={{ pages.prev_num }}">&gt;</a>
                </li>
            </ul>
        </nav>
    </div>
{% endblock %}