admin/src/web/controllers/disciplinas.py
from flask import render_template, request, Blueprint, flash, redirect, url_for, session
from sqlalchemy import asc, desc
from src.core.business.models import Disciplina
from src.core.fees import socio_moroso
from src.core import business, config, auth
from src.web.controllers.forms import AltaDisciplinaForm, AltaCategoriaForm, AltaInstructorForm, EditarDisciplinaForm
from src.web.helpers.auth import login_required
from src.web.helpers.roles import permission_required
from src.core.auth import get_all_socios
from src.web.helpers import pagination



disciplina_blueprint = Blueprint("disciplinas", __name__, url_prefix="/disciplinas")


@disciplina_blueprint.route("/",methods=["GET","POST"])
@login_required
@permission_required(perm="discipline_index")
def disciplinas_listado():
    """listado de todas las disciplinas con sus datos"""
    page = request.args.get('page')

    if page and page.isdigit():
        page = int(page)
    else:
        page = 1
    disciplinas = business.list_disciplinas_categorias_instructor()
    
    order = True if config.get_configuration().criterio == "asc" else False
    if order:
        disciplinas = disciplinas.order_by(Disciplina.nombre_disciplina.asc(), Disciplina.habilitada.desc())
    else:
        disciplinas = disciplinas.order_by(Disciplina.nombre_disciplina.desc(), Disciplina.habilitada.desc())

    pages = disciplinas.paginate(page=page, per_page=config.ELEM_PER_PAGE())
    return render_template('business/disciplinas.html',pages=pages)


@disciplina_blueprint.route("/alta", methods=["GET","POST"])
@login_required
@permission_required(perm="discipline_new")
def alta_disciplina():
    """Da de alta una disciplina si se provee nombre de la disciplina, costo, detalle de los dias,
        un instructor y una categoria"""
    form1 = AltaDisciplinaForm()
    form2 = AltaCategoriaForm()
    form3 = AltaInstructorForm()
    if(request.method == 'POST'):
        if(form1.validate_on_submit() and form2.validate_on_submit() and form3.validate_on_submit()):
            try:
                instructor = business.get_instructor(form3.nombre_instructor.data,form3.apellido_instructor.data)
                if (instructor == None):
                    instructor = business.load_instructor(nombre_instructor = form3.nombre_instructor.data, 
                                                            apellido_instructor = form3.apellido_instructor.data) 
                categoria = business.get_categoria(descripcion = form2.descripcion.data)
                if(categoria == None):
                    categoria = business.load_categoria(descripcion = form2.descripcion.data)
                    
                disciplina = business.load_disciplina(habilitada = form1.habilitada.data,
                                                        detalle = form1.detalle.data,
                                                            nombre_disciplina = form1.nombre_disciplina.data,
                                                                costo = form1.costo.data)

                business.assign_instructores(disciplina,[instructor])
                business.assign_categorias(disciplina,[categoria])
                flash(f'La disciplina {form1.nombre_disciplina.data} se creo correctamente','success')
                return redirect(url_for('disciplinas.disciplinas_listado'))
            except:
                flash(f'La disciplina no pudo ser creada','error')
                return redirect(url_for("disciplinas.alta_disciplina"))
    return render_template('business/alta_disciplinas.html',form1=form1,form2=form2,form3=form3)


@disciplina_blueprint.route("/editar/<id>", methods=["GET","POST"])
@login_required
@permission_required("discipline_update")
def editar_disciplina(id):
    """Permite editar disciplinas, modificando la informacion existente o 
                            agregando instructores o categorias a la disciplina"""
    disciplina_to_update = business.get_disciplina_by_id(id)
    categorias = business.list_categorias_from_disciplina_id(id)
    instructores = business.list_instructores_from_disciplina_id(id)

    form = EditarDisciplinaForm(obj=disciplina_to_update)
    
    if request.method == "POST":
        if(form.validate_on_submit()):
            disciplina_to_update.nombre_disciplina = form.nombre_disciplina.data
            disciplina_to_update.costo = form.costo.data
            disciplina_to_update.detalle = form.detalle.data
            disciplina_to_update.habilitada = form.habilitada.data
        try:
            business.update_disciplina(disciplina_to_update)
            message = "Disciplina {} actualizada".format(disciplina_to_update.nombre_disciplina)
            flash(message, "success")
            return redirect(url_for("disciplinas.disciplinas_listado"))
        except:
            flash("Error, intente de vuelta", "error")
            return render_template('business/editar_disciplina.html', form=form)

    return render_template('business/editar_disciplina.html', disciplina_to_update = disciplina_to_update,form=form,categorias = categorias, instructores=instructores)


@disciplina_blueprint.route("/delete/<id>", methods=["GET", "POST"])
@login_required
@permission_required(perm="discipline_destroy")
def delete_disciplina(id):
    """Elimina la disciplina seleccionada"""

    disciplina_to_delete = business.get_disciplina_by_id(id)
    try:
        business.delete_disciplina(disciplina_to_delete)
        message = "Disciplina {} eliminada".format(disciplina_to_delete.nombre_disciplina)
        flash(message,"success")
        return redirect(url_for("disciplinas.disciplinas_listado"))
    except:
        flash("Error, intente de vuelta","error")
        return redirect(url_for("disciplinas.disciplinas_listado"))


@disciplina_blueprint.route("/editar/desvincular_categoria/<id>/<idc>", methods=["GET", "POST"])
@login_required
@permission_required("discipline_update")
def desvincular_categoria(id,idc):
    """Desvincula una categoria de una disciplina quedando disponible para las disciplinas que aun la contienen"""

    disciplina = business.get_disciplina_by_id(id)
    categoria = business.get_categoria_by_id(idc)
    if(categoria and disciplina):
        try:
            business.unlink_categorias(disciplina,categoria)
            message = f"Se elimino la categoria de la disciplina {disciplina.nombre_disciplina}"
            flash(message,"success")
            return redirect(url_for("disciplinas.editar_disciplina",id=id,idc=idc))
        except:
            flash("Error, intente de vuelta","error")
            return redirect(url_for("disciplinas.editar_disciplina",id=id,idc=idc))


@disciplina_blueprint.route("/editar/desvincular_instructor/<id>/<idi>", methods=["GET", "POST"])
@login_required
@permission_required("discipline_update")
def desvincular_instructor(id,idi):
    """Desvincula un instructor de una disciplina quedando disponible para las disciplinas que aun lo contienen"""

    disciplina = business.get_disciplina_by_id(id)
    instructor = business.get_instructor_by_id(idi)
    if(disciplina and instructor):
        try:
            business.unlink_instructor(disciplina,instructor)
            message = f"Se elimino el instructor de la disciplina {disciplina.nombre_disciplina}"
            flash(message,"success")
            return redirect(url_for("disciplinas.editar_disciplina",id=id,idi=idi))
        except:
            flash("Error, intente de vuelta","error")
            return redirect(url_for("disciplinas.editar_disciplina",id=id,idi=idi))


@disciplina_blueprint.route("/editar/alta_instructor/<id>", methods=["GET", "POST"])
@login_required
@permission_required("discipline_update")
def alta_instructor(id):
    """ Permite dar de alta a un instructor en una disciplina en la edición de dsiciplinas """

    disciplina = business.get_disciplina_by_id(id)
    form = AltaInstructorForm()
    if(request.method == 'POST'):
        if(form.validate_on_submit()):
            nombre_instructor = form.nombre_instructor.data
            apellido_instructor = form.apellido_instructor.data
            instructor = business.get_instructor(nombre_instructor,apellido_instructor)
            if (instructor == None):
                    instructor = business.load_instructor(nombre_instructor = nombre_instructor, 
                                                            apellido_instructor = apellido_instructor)
            try:
                business.assign_instructores(disciplina,[instructor])
                flash(f'El instructor {nombre_instructor}  {apellido_instructor }se asoció correctamente a {disciplina.nombre_disciplina}','success')
                return redirect(url_for("disciplinas.editar_disciplina",id=id))
            except:
                flash("Error, intente de vuelta","error")
                return render_template('business/alta_instructor.html',form=form,id=id)
    return render_template('business/alta_instructor.html',form=form, id=id)


@disciplina_blueprint.route("/editar/alta_categoria/<id>", methods=["GET", "POST"])
@login_required
@permission_required("discipline_update")
def alta_categoria(id):
    """ Permite dar de alta a una categoria en una disciplina en la edición de disciplinas"""

    disciplina = business.get_disciplina_by_id(id)
    form = AltaCategoriaForm()
    if(request.method == 'POST'):
        if(form.validate_on_submit()):
            descripcion = form.descripcion.data
            categoria = business.get_categoria(descripcion)
            if (categoria == None):
                    categoria = business.load_categoria(descripcion=descripcion)
            try:
                business.assign_categorias(disciplina,[categoria])
                flash(f'La categoria {descripcion} se asoció correctamente a {disciplina.nombre_disciplina}','success')
                return redirect(url_for("disciplinas.editar_disciplina", id=id))
            except:

admin/src/web/controllers/user.py
from flask import render_template, Blueprint, flash, request, redirect, url_for, session
from src.core.auth.models import User
from src.web.helpers import pagination
from src.core import auth, roles, config
from src.web.controllers.forms import RegisterUserByAdminForm, EditUserByAdminForm
from src.web.helpers.auth import login_required
from src.web.helpers.choices_loader import load_roles, load_user_estados
from src.web.helpers.roles import permission_required

user_blueprint = Blueprint("user", __name__, url_prefix="/user")

# List Users
@user_blueprint.route("/index", methods=["GET", "POST"])
@login_required
@permission_required(perm="user_index")
def index_users():
    '''Manejador de vista que muestra un listado con todos los usuarios, permitiendo realizar
    búsquedas por distintos criterios'''
        
    users = auth.list_users()
    order = True if config.get_configuration().criterio == "asc" else False
    if order:
        users = users.order_by(User.apellido.asc(), User.estado.desc())
    else:
        users = users.order_by(User.apellido.desc(), User.estado.desc())
        
    pages = users.paginate(page=pagination.pagination(), per_page=config.ELEM_PER_PAGE())

    return render_template("user/base_listado_usuarios.html", pages=pages, added="index")


# Create Users
@user_blueprint.route("/create", methods=["GET", "POST"])
@login_required
@permission_required(perm="user_new")
def create_user():
    form = RegisterUserByAdminForm()
    form.roles.choices = load_roles()
    if form.validate_on_submit(): 
        user_to_create = auth.get_exact_user(username=form.username.data, email=form.email.data)
        if(user_to_create == None):
            auth.load_user(username = form.username.data,
                            email = form.email.data,
                            nombre = form.name.data.capitalize(),
                            apellido = form.lastname.data.capitalize(),
                            password = form.password.data)
            flash("Usuario agregado", "success")
            return redirect(url_for("user.index_users"))
        else:
            if(user_to_create.email == form.email.data):
                message = "El mail {} ya existe".format(user_to_create.email)
                flash(message, "error")
            elif(user_to_create.username == form.username.data):
                message = "El usuario {} ya existe".format(user_to_create.username)
                flash(message, "error")
            return redirect(url_for("user.create_user"))
    return render_template("user/alta_usuarios.html", form=form)


# Update Users
@user_blueprint.route("/edit/<int:id>", methods=["GET", "POST"])
@login_required
@permission_required(perm="user_update")
def edit_user(id):
    user_to_update = auth.get_user_id(id)
    if id == 1 or user_to_update.username == session["username"]:
        flash("No se puede editar el usuario seleccionado", "error")
        return redirect(url_for("user.index_users"))
    form = EditUserByAdminForm(obj=user_to_update)
    form.estado.choices = load_user_estados()
    form.roles.choices = load_roles()
    form.password = user_to_update.password
    if form.validate_on_submit():
        # User new data
        user_to_update.nombre = request.form['name'].capitalize()
        user_to_update.apellido = request.form['lastname'].capitalize()
        user_to_update.username = request.form['username']
        user_to_update.email = request.form['email']
        user_to_update.estado = False if request.form['estado'] == 'False' else True
        if(form.roles.data is not None):
            added = []
            for nombre_rol in form.roles.data:
                next = roles.get_rol_by_name(nombre_rol)
                added.append(next)
            roles.assign_roles(user_to_update, added)
        
        # Update user in db
        try:
            auth.update_user(user_to_update)
            message = "Usuario {} actualizado".format(user_to_update.username)
            flash(message, "success")
            return redirect(url_for("user.index_users"))
        except:
            flash("Error, intente de vuelta", "error")
            return render_template("user/editar_usuarios.html", form=form, user_to_update=user_to_update)
    return render_template("user/editar_usuarios.html", form=form, user_to_update=user_to_update)

# Delete Users
@user_blueprint.route("/delete/<int:id>")
@login_required
@permission_required("user_destroy")
def delete_user(id):
    user_to_delete = auth.get_user_id(id)
    try:
        auth.delete_user(id)
        message = "Usuario {} eliminado".format(user_to_delete.username)
        flash(message, "success")
        return redirect(url_for("user.index_users"))
    except:
        flash("Error, intente de vuelta", "error")
        return redirect(url_for("user.index_users"))


# Search Users Function
@user_blueprint.route('/search', methods=["GET", "POST"])
@login_required
@permission_required(perm="user_show")
def search():
    params = request.form
    session['estado'] = params.get('estado')
    session['searched'] = params.get('searched')
    
    return redirect(url_for('user.search_results'))

@user_blueprint.get("/search_results")
@login_required
@permission_required(perm="user_show")
def search_results():
    '''Filtra los usuarios según los criterios ingresados'''
    users = auth.list_users()

    order = True if config.get_configuration().criterio == "asc" else False
    if order:
        users = users.order_by(User.apellido.asc(), User.estado.desc())
    else:
        users = users.order_by(User.apellido.desc(), User.estado.desc())

    searched = session['searched']
    estado = session['estado']
    if not searched and estado == 'todos':
        flash("Ingrese o seleccione un criterio para realizar una búsqueda", "info")
        return redirect(url_for("user.index_users"))
    
    if searched:
        users = auth.get_by_search_string(users, searched)
    
    if estado != 'todos':
        if estado == 'True':
            users = auth.get_by_estado(users, True)
        else:
            users = auth.get_by_estado(users, False)
    
    if(users.count() == 0):
        flash("No se ha encontrado ningún usuario con el criterio ingresado", "error")
        return redirect(url_for('user.index_users'))
    
    pages = users.paginate(page=pagination.pagination(), per_page=config.ELEM_PER_PAGE())
    return render_template("user/buscar_usuario.html", pages=pages, s=estado, n=searched, added="search_results")

admin/src/web/templates/business/alta_categoria.html
{% extends "base.html" %}
{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/form_alta.css') }}">
{% endblock %}
{% set active_page = "disciplinas" %}
{% from "macros.html" import check_errors %}

{% if has_permission("discipline_update") %}
  {% block title %} 
      Alta de Categoria
  {% endblock %}

  {% block content %}
    <div class="container py-5 form_width">
      <h1 class="text-center fw-semibold mb-4">Registrar categoria</h1>
      <form name="altaCategoria needs-validation" method="POST">
          {{ form.csrf_token }}
              <div class="mb-2">
                <div class="d-grid gap-2 gap-md-4 d-md-flex justify-content-md-center">
                  <div class="col">
                    <label for="nombre categoria" class="form-label">{{ form.descripcion.label }}</label>
                    {{ form.descripcion(class_="form-control", size=32) }}
                        {{ check_errors(form.descripcion) }}
                  </div>
                </div>
              </div>
          <div class="d-grid gap-2 d-md-flex justify-content-md-center mt-auto py-4">
          <a class="btn btn-dark" href="{{ url_for('disciplinas.editar_disciplina',id=id)}}">Volver a edición de disciplinas</a>
          <button type="submit" class="btn btn-dark">Dar de alta</button>
      </form>
  </div>   
  {% endblock %}
{% endif %}

admin/src/web/templates/business/disciplinas.html
{% extends "base.html" %}
{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/index.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/modal.css') }}">

    <style>
        @media only screen and (max-width: 767px),
        (min-device-width: 768px) and (max-device-width: 995px)  {
                /*
            Label the data
            */
            td:nth-of-type(1):before { content: "#"; }
            td:nth-of-type(2):before { content: "Nombre"; }
            td:nth-of-type(3):before { content: "Dias y horarios"; }
            td:nth-of-type(4):before { content: "Costo"; }
            td:nth-of-type(5):before { content: "Habilitada"; }
            td:nth-of-type(6):before { content: "Categoria"; }
            td:nth-of-type(7):before { content: "Instructores"; }
            td:nth-of-type(8):before { content: "Opciones"; }
        }

    </style>
{% endblock %}
{% set active_page = "disciplinas" %}

{% if has_permission("discipline_index") %}
    {% block title %}Listado de disciplinas{% endblock %}

    {% block content %}
        <div class="container py-5 justify-content-center"> 
            <h1 class="text-center fw-semibold mb-4" id="mHeader">Listado de disciplinas</h1>
            <div class="table table-dark">
                <table class="">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Nombre</th>
                            <th>Dias y horarios</th>
                            <th>Costo</th>
                            <th>Habilitada</th>
                            <th>Categoria</th>
                            <th>Instructores</th>
                            <th>Opciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for disciplina in pages.items %} 
                            <tr>
                                <td>{{ disciplina.id }}</td>
                                <td>{{ disciplina.nombre_disciplina }} </td>
                                <td>{{ disciplina.detalle}}</td>
                                <td>$ {{ disciplina.costo }} </td>
                                <td>{% if disciplina.habilitada %} Si
                                    {% else %} No
                                    {% endif %}
                                </td>
                                <td> 
                                    <div class="dropdown">
                                        <button class="btn btn-sm btn-especial dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                            Categorías
                                        </button>
                                        <ul class="dropdown-menu">
                                            {% for categoria in disciplina.categorias %}
                                                <li><a class="dropdown-item" href="#">{{categoria.descripcion}}</a></li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                </td>
                                <td>
                                    <div class="dropdown">
                                        <button class="btn btn-sm btn-especial dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                            Instructores
                                        </button>
                                        <ul class="dropdown-menu">
                                            {% for instructor in disciplina.instructores %}
                                                <li><a class="dropdown-item" href="#">{{ instructor.nombre_instructor}} {{ instructor.apellido_instructor}}</a></li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                </td>
                                <td>
                                    <div class="d-grid gap-2 d-md-flex justify-content-xl-center justify-content-start mt-auto">
                                        {% if has_permission("discipline_update") %}
                                            <a href="{{ url_for('disciplinas.inscripcion_socio', id = disciplina.id) }}">
                                                <button type="button" class="btn btn-sm btn-inscribir">Inscribir socio</button>
                                            </a>

                                            <a href="{{ url_for('disciplinas.editar_disciplina', id = disciplina.id) }}">
                                                <button type="button" class="btn btn-sm btn-especial">Editar</button>
                                            </a>
                                        {% endif %}
                                        
                                        {% if has_permission("discipline_destroy") %}
                                            <!-- Button trigger modal -->
                                            <button type="button" class="btn  btn-sm btn-borrar" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
                                                Eliminar
                                            </button>
                                        {% endif %}
                                    </div>

                                    <!-- Modal -->
                                    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                <h1 class="modal-title fs-5">Confirmación de eliminación</h1>
                                                </div>
                                                <div class="modal-body">
                                                    <p>¿Está segur@ que desea eliminar la disciplina?</p>
                                                </div>
                                            
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                                                    <a href="{{ url_for('disciplinas.delete_disciplina', id = disciplina.id) }}">
                                                        <button type="button" class="btn btn-danger">Eliminar</button>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            {% endblock %}
            {% block buttons %}
                <div class="d-grid gap-4 d-md-flex align-items-center justify-content-md-between mt-auto pt-4 pb-2">
                    <!--Paginación-->
                    <div class="d-md-flex justify-content-md-start">
                        {% include "paginacion.html" %}
                    </div>
                    {% if has_permission("discipline_new") %}
                        <!--Agregar disciplina-->
                        <a href="{{ url_for('disciplinas.alta_disciplina') }}">
                            <button type="button" class="btn btn-dark">Agregar disciplina</button>
                        </a>
                    {% endif %}
                </div>
            {% endblock %}
        </div>
{% endif %}

admin/src/web/templates/business/editar_disciplina.html
{% extends "base.html" %}
{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/form_alta.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/index.css') }}">

    <style>
        @media only screen and (max-width: 767px),
        (min-device-width: 768px) and (max-device-width: 995px)  {
                /*
            Label the data
            */
            td:nth-of-type(1):before { content: "Nombre"; }
            td:nth-of-type(2):before { content: "Opciones"; }
        }

        #mHeader{
            padding-bottom: 70px;
        }
    </style>
{% endblock %}
{% from "macros.html" import check_errors %}
{% set active_page = "disciplinas" %}

{% if has_permission("discipline_update") %}

    {% block title %} 
        Editar Disciplina
    {% endblock %}

    {% block content %}
      <div class="container py-5 form_width">
        <h1 class="text-center fw-semibold mb-4">Editar disciplina</h1>
        <form name="altaDisciplina needs-validation" method="POST">
          {{ form.csrf_token }}
            
          <div class="form-group">
                <div class="mb-2">
                    <div class="d-grid gap-2 gap-md-4 d-md-flex justify-content-md-center">
                        <div class="col">
                            <label for="nombre" class="form-label">{{ form.nombre_disciplina.label }}</label>
                            {{ form.nombre_disciplina(class_="form-control", size=32) }}
                            {{ check_errors(form.nombre_disciplina) }} 
                        </div>
                        <div class="col">
                            <label for="costo" class="form-label">{{ form.costo.label }}</label>
                            {{ form.costo(class_="form-control", size=32) }}
                            {{ check_errors(form.costo) }} 
                        </div>
                    </div> 
                </div>
                <br>
                <div class="mb-2">
                  
                  <div class="col">
                    <label for="detalle" class="form-label">{{ form.detalle.label }}</label>
                    {{ form.detalle(class_="form-control", size=32) }}
                    {{ check_errors(form.detalle) }} 
                  </div>
                  <br>
                  {{form.habilitada}}
                  <label for="detalle" class="form-label">{{ form.habilitada.label }}</label>
                  
                </div>
                <br>
                <div class="table table-dark rounded-3 overflow-hidden">
                  <h4 class="py-1">Categorías</h4>
                  <table class="">
                      <thead>
                          <tr>
                              <th style="width: 50%;">Nombre</th>
                              <th>Opciones</th>
                          </tr>
                      </thead>
                      <tbody>
                        {% for item in categorias %} 
                          {% for categoria in item.categorias %}
                            <tr>
                              <td>{{categoria.descripcion}}</td>
                              <td> 
                                <a class="btn btn-sm btn-borrar" href="{{ url_for('disciplinas.desvincular_categoria',id = disciplina_to_update.id, idc = categoria.id) }}">Eliminar</a>
                              </td>
                            </tr>  
                          {% endfor %}
                        {% endfor %}
                      </tbody>
                  </table>
                </div>
                <div class="d-grid gap-2 d-md-flex justify-content-md-center mt-auto py-4">
                  <a class="btn btn-dark" href="{{ url_for('disciplinas.alta_categoria',id=disciplina_to_update.id)}}">Agregar Categoria</a>
                </div>
                <h4 class="py-1">Instructores</h4>
                <div class="table table-dark rounded-3 overflow-hidden">
                  <table class="">
                      <thead>
                        <tr>
                          <th style="width: 50%">Nombre</th>
                          <th>Opciones</th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for item in instructores %}
                          {% for instructor in item.instructores %}
                          <tr>
                            <td>{{instructor.nombre_instructor}} {{instructor.apellido_instructor}}</td>
                            <td>
                              <a class="btn btn-sm btn-borrar" href="{{ url_for('disciplinas.desvincular_instructor',id = disciplina_to_update.id, idi = instructor.id) }}">Eliminar</a>
                            </td>
                          </tr>
                          {% endfor %}
                        {% endfor %}
                      </tbody>
                  </table>
              </div>
              <div class="d-grid gap-2 d-md-flex justify-content-md-center mt-auto py-4">
                <a class="btn btn-dark" href="{{ url_for('disciplinas.alta_instructor',id=disciplina_to_update.id)}}">Agregar Instructor</a>
              </div>

              <div class="d-grid gap-2 d-md-flex justify-content-md-center mt-auto pt-4">
                <a class="btn btn-dark" href="{{ url_for('disciplinas.disciplinas_listado')}}">Volver a disciplinas</a>
                <button type="submit" class="btn btn-dark">Actualizar</button>
              </div> 
            </div>
               
        </form>
      </div>
    {% endblock %}
{% endif %}