admin/src/web/controllers/cuotas.py
import platform
from flask import Blueprint, render_template, redirect, request, session, url_for, flash
from datetime import datetime
from src.core.auth.models import Socio
from src.core.fees.models import Cuota
from src.web.helpers.roles import permission_required
from src.web.helpers.auth import login_required
from src.web.helpers import pagination
from src.web.helpers.formatters import generar_informacion
from src.core import auth
from src.core import fees
from src.core import config
from src.web.controllers import exporter

cuotas_blueprint = Blueprint("pagos", __name__, url_prefix="/pagos")

@cuotas_blueprint.route("/", methods=["GET", "POST"])
@login_required
@permission_required(perm="payments_index")
def searcher():
    '''Renderer de barra de búsqueda de socios para mostrar sus cuotas.
    Se muestra un listado de todas las cuotas del mes.'''
        
    cuotas = fees.get_cuotas_mes(datetime.now())
    cuotas = fees.cuotas_format(cuotas)
    
    exists = True if cuotas.count() > 0 else False

    order = True if config.get_configuration().criterio == "asc" else False
    if order:
        cuotas = cuotas.order_by(Socio.apellido.asc(), Cuota.estado.desc())
    else:
        cuotas = cuotas.order_by(Socio.apellido.desc(), Cuota.estado.desc())
        
    pages = cuotas.paginate(page=pagination.pagination(), per_page=config.get_configuration().cant_elem)
    
    pendings = True if fees.exist_pendings() else False

    return render_template("cuotas/searcher.html", cuotas=cuotas, exists=exists, pages=pages, pendings=pendings)

@cuotas_blueprint.route("/search", methods=["GET", "POST"])
@login_required
@permission_required(perm="payments_show")
def search():
    '''Guarda el input ingresado en la búsqueda de socios para listar sus cuotas 
    y redirecciona a la función que muestra los resultados.'''    

    session["input"] = request.form["input"] 
    return redirect(url_for("pagos.search_results")) 

@cuotas_blueprint.get("/search_results") 
@login_required
@permission_required(perm="payments_show")
def search_results():
    '''Listado de todos los pagos del/los socio/s indicado/s'''
    
    input = session.get("input")
    amount_socios, type_id= auth.get_socios_by_lastname_or_id(input)
        
    if amount_socios == 0:
        flash("No existe un socio con dicho número de socio o apellido", "error")
        return redirect(url_for("pagos.searcher"))

    cuotas = fees.get_cuotas_socios(input, type_id) 
    if cuotas.count() == 0:
        flash("El socio indicado aún no dispone de cuotas pagas ni impagas", "info")
        return redirect(url_for("pagos.searcher"))
    
    order = True if config.get_configuration().criterio == "asc" else False
    
    if order:
        cuotas = cuotas.order_by(Socio.apellido.asc(), Cuota.estado.desc())
    else:
        cuotas = cuotas.order_by(Socio.apellido.desc(), Cuota.estado.desc())
    pages = cuotas.paginate(page=pagination.pagination(), per_page=config.ELEM_PER_PAGE())

    return render_template("cuotas/index.html", cuotas=cuotas, pages=pages, exists=True)

@cuotas_blueprint.get("/pendings")
@login_required
@permission_required(perm="payments_index")
def index_pendings():
    '''Listado de todas las cuotas pendientes'''

    cuotas = fees.get_cuotas_pendientes()
    if cuotas.count() == 0:
        flash("No existen cuentas pendientes", "success")
        return redirect(url_for("pagos.searcher"))

    order = True if config.get_configuration().criterio == "asc" else False

    if order:
        cuotas = cuotas.order_by(Cuota.id.asc())
    else:
        cuotas = cuotas.order_by(Cuota.id.desc())
    pages = cuotas.paginate(page=pagination.pagination(), per_page=config.ELEM_PER_PAGE())
    
    return render_template("cuotas/index_pendings.html", cuotas=cuotas, pages=pages, exists=cuotas.count() > 0)

@cuotas_blueprint.get("/show_payment/<id>")
@login_required
@permission_required(perm="payments_import")
def show_pending_payment(id):
    '''Muestra foto de comprobante de cuota pendiente'''
    
    cuota = fees.cuota(id)
    file = cuota.comprobante.split("\\")[-1]
    if platform.system() == 'Windows':
        path = '../../../../public/images/comprobantes/' + file
    # Linux or MacOs
    elif platform.system() == 'Linux' or platform.system() == 'Darwin':
        path = '../../../../' + file
    return render_template("cuotas/pending_payment.html", path=path, cuota=cuota)

@cuotas_blueprint.get("/show_payment/<id_cuota>/<selected>")
@login_required
@permission_required(perm="payments_import")
def accept_or_deny_payment(id_cuota, selected):
    if selected == 'Accept':
        return redirect(url_for("pagos.pagar_cuota", id_cuota=id_cuota))
    else:
        cuota = fees.cuota(id_cuota)
        cuota.estado = "Impaga"
        fees.update_cuota(cuota)
        flash("Cuota RECHAZADA con éxito", "success")
        return redirect(url_for('pagos.searcher'))

@cuotas_blueprint.get("/socio/<id>")
@login_required
@permission_required(perm="payments_index")
def cuotas_socio(id):
    '''Listado de todos los pagos del socio indicado.'''

    cuotas = fees.get_cuotas_socios(id, True)
    if cuotas.count() == 0:
        flash("El socio indicado aún no dispone de cuotas pagas ni impagas", "success")
        return redirect(url_for("socios.index_socios"))
        
    order = True if config.get_configuration().criterio == "asc" else False
    if order:
        cuotas = cuotas.order_by(Socio.apellido.asc(), Cuota.estado.desc())
    else:
        cuotas = cuotas.order_by(Socio.apellido.desc(), Cuota.estado.desc())
    pages = cuotas.paginate(page=pagination.pagination(), per_page=config.ELEM_PER_PAGE())

    return render_template("cuotas/index.html", cuotas=cuotas, pages=pages, exists=True)

@cuotas_blueprint.get("/generate_cuotas")
@login_required
@permission_required(perm="payments_import")
def create_cuotas():
    '''Genera las cuotas del mes para todos los socios que aún no dispongan de una cuota en el mes actual'''

    counter = fees.generate_cuotas()
    if counter == 0:
        flash("No se han generado cuotas porque no existen socios cargados o porque todos los socios activos ya tienen una cuota para este mes", "success")
    elif counter == 1:
        flash("Se ha generado una cuota", "success")
    else:
        flash(f"Se han generado {counter} cuotas", "success")

    return redirect(url_for("pagos.searcher"))

@cuotas_blueprint.get("/pagar_cuota/<id_cuota>")
@login_required
@permission_required(perm="payments_import")
def pagar_cuota(id_cuota):
    '''Pago de la cuota indicada por parámetro'''

    res = fees.pagar_cuota(fees.cuota(id_cuota))
    if res is False:
        flash(f"La cuota #{id_cuota} ya se encuentra pagada", "error")
        return redirect(url_for("pagos.searcher"))

    flash(f"Se ha realizado el pago de la cuota #{id_cuota} con éxito", "success")
    return redirect(url_for("pagos.show_info_cuota", id_cuota=id_cuota))

@cuotas_blueprint.get("cuota/<id_cuota>")
@login_required
@permission_required(perm="payments_show")
def show_info_cuota(id_cuota):
    '''Muestra en pantalla toda la información de la cuota que tiene el id recibido
    como parámetro.
    Si la cuota está pagada, se muestra en formato de recibo de pago.'''

    cuota = fees.cuota(id_cuota)
    
    informacion = generar_informacion(cuota)
    if cuota.estado == "Pagada":
        session['cuota_info'] = informacion
        informacion["recibo_txt"] = config.get_configuration().recibo_txt
        return render_template("cuotas/show_comprobante.html", comprobante=informacion)
    elif cuota.estado == "Pendiente":
        return redirect(url_for("pagos.show_pending_payment", id=cuota.id))
    else:
        return render_template("cuotas/informacion.html", informacion=informacion)
    
@cuotas_blueprint.get("/download")
@login_required
@permission_required(perm="payments_show")
def download():
    informacion = session['cuota_info']
    return exporter.cuota_pdf_report(informacion)

admin/src/web/templates/cuotas/export_comprobante.html
{% if has_permission("payments_show") %}
<!doctype html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Comprobante de pago</title>
</head>


<body>
    <div class="container">
        <div class="panel panel-default"> 
            <div class="col-4"> 
                <img src="data:;base64,{{ get_image_file_as_base64_data() }}">
                {% if comprobante.recibo_txt %}
                    <span class="mensaje_recibo">"{{comprobante.recibo_txt}}"</span>
                {% endif %}
            </div>
            <div class="container">
              <div class="col-8">
                <div class="panel-body">
                    <h4 class="panel-title"><strong>Número de cuota: #{{comprobante.id}}</strong></h4>
                    <p><strong>Socio:</strong> {{comprobante.nombre}}</p> 
                    <p><strong>Nro. de socio:</strong> {{ comprobante.socio }}</p>
                    <p><strong>Fecha de creación:</strong> {{ comprobante.fecha_creacion }}</p>
                    {% if comprobante.fecha_pago|length %}
                        <p><strong>Fecha de pago:</strong> {{ comprobante.fecha_pago}}</p>
                    {% else %}
                        <p><strong>Estado:</strong> impaga</p>
                    {% endif %}
                    <p>La cuota cubre los siguientes gastos:</p>
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Motivo</th>
                                <th>Costo</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Valor de cuota base</td>
                                <td>{{ comprobante.detalle.base }}</td>
                            </tr>
                            <tr>
                                {% if comprobante.detalle.recargo != 0 %}
                                    <td>Recargo por deudas</td>
                                    <td>{{ comprobante.detalle.recargo }}</td>
                                {% endif %}
                            </tr>
                            {% for key, value in comprobante.detalle.disciplinas.items() %}
                                <tr>
                                    <td>{{ key }}</td>
                                    <td>{{ value}}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    <hr>
                    <p><strong>Monto total:</strong> ${{ comprobante.monto}}</p>
                    <div class="panel-footer text-muted"><strong>Última modificación:</strong> {{ comprobante.fecha_mod}}</div>
                </div>
            </div>
            </div>
        </div>
    </div>
</body>
{% endif %}

admin/src/web/templates/cuotas/index.html
{% extends "/cuotas/searcher.html" %}
{% if has_permission("payments_show") %}
    {% block title %}Resultados de búsqueda{% endblock %}
    {% block header_title %}
        <h1 class="text-center fw-semibold mb-4">Resultados de búsqueda</h1>
    {% endblock %}
    {% block button_bottom %} 
        <div class="d-grid gap-2 d-md-flex justify-content-md-center mt-auto pt-2">
            <a class="btn btn-dark" href="{{ url_for('pagos.searcher') }}">Volver al listado general de cuotas</a>
        </div>
    {% endblock %}
{% endif %}

admin/src/web/templates/cuotas/index_pendings.html
{% extends "base.html" %}
{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/index.css') }}">

    <style>
        @media only screen and (max-width: 767px),
        (min-device-width: 768px) and (max-device-width: 995px)  {
                /*
            Label the data
            */
            td:nth-of-type(1):before { content: "Socio"; }
            td:nth-of-type(2):before { content: "Mes a abonar"; }
            td:nth-of-type(3):before { content: "Opciones"; }
        }
    </style>
{% endblock %}
{% set active_page = "pagos" %}

{% if has_permission("payments_index") %}
    {% block title %}Cuotas pendientes{% endblock %}

    {% block content %}
        <div class="container pt-5 justify-content-center">
            {% block header_title %}<h1 class="text-center fw-semibold mb-4">Cuotas pendientes</h1>{% endblock %}
            {% if exists %}
                <div class="table table-dark">
                    <table class="">
                        <thead>
                            <tr>
                                <th>Socio</th>
                                <th>Mes a abonar</th>
                                <th>Opciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for cuota in pages.items %} 
                                <tr>
                                    <td>{{cuota.socio_id}}</td>
                                    <td>{{cuota.created_at|datetime_format('%m-%Y')}}</td>
                                    <!--Más info-->
                                    <td>
                                        <div class="d-grid gap-2 d-md-flex justify-content-lg-center justify-content-start mt-auto">
                                            {% if has_permission("payments_show") %}
                                                <a class="btn btn-sm btn-inscribir" href="{{ url_for('pagos.show_pending_payment', id = cuota.id) }}">
                                                    Comprobante
                                                </a>
                                            {% endif %}
                                        </div>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% else %}
                <h1>NO HAY CUOTAS PENDIENTES</h1>
            {% endif %}
        </div>        
    {% endblock %}
    {% block buttons %}
        <div class="d-grid gap-4 d-md-flex justify-content-md-between mt-auto pt-4 pb-2">
            {% include "paginacion.html" %}
        </div>
        {% block button_bottom %}
            <div class="d-grid gap-2 d-md-flex justify-content-md-center mt-auto pt-2 pb-2">
                <a href="{{ url_for('pagos.searcher') }}" class="btn btn-dark">Volver al listado de cuotas</a> 
            </div>
        {% endblock %}
    {% endblock %}
{% endif %}

admin/src/web/templates/cuotas/pending_payment.html
{% extends "base.html" %}

{% set active_page = "cuotas" %}
{% if has_permission("payments_import") %}
    {% block title %}Comprobante de la cuota{% endblock %}

    {% block content %}
        <div class="container-fluid py-5">
            <h1 class="text-center fw-semibold mb-5">Comprobante de pago de cuota {{cuota.id}}</h1>
            <div class="d-flex justify-content-center">
                <iframe src="{{path}}" width="70%" height="500" title="Comprobante de pago" ></iframe> <!--src="../../../../public/images/comprobantes/{{file}}"-->
            </div>
            <div class="d-grid gap-2 d-md-flex justify-content-md-center mt-auto py-4">
                <a class="btn btn-success" href="{{ url_for('pagos.accept_or_deny_payment', id_cuota = cuota.id, selected='Accept') }}">Aceptar</a>
                <a class="btn btn-borrar" href="{{ url_for('pagos.accept_or_deny_payment', id_cuota = cuota.id, selected='Deny') }}">Rechazar</a>
            </div>
            <div class="d-grid gap-2 d-md-flex justify-content-md-center mt-auto py-4">
                <a class="btn btn-dark" href="{{ url_for('pagos.index_pendings') }}">Volver al listado de cuotas pendientes</a>
            </div>
        </div>
    {% endblock %}
{% endif %}

admin/src/web/templates/cuotas/searcher.html
{% extends "base.html" %}
{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/index.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/modal.css') }}">

    <style>
        @media only screen and (max-width: 767px),
        (min-device-width: 768px) and (max-device-width: 995px)  {
                /*
            Label the data
            */
            td:nth-of-type(1):before { content: "Socio"; }
            td:nth-of-type(2):before { content: "Monto"; }
            td:nth-of-type(3):before { content: "Estado"; }
            td:nth-of-type(4):before { content: "Mes a abonar"; }
            td:nth-of-type(5):before { content: "Opciones"; }
        }
    </style>
{% endblock %}
{% set active_page = "pagos" %}

{% if has_permission("payments_index") %}
    {% block title %}Buscar cuotas de socios{% endblock %}

    {% block content %}
        <div class="container pt-5 justify-content-center">
            {% if pendings %}
                <div class="card mb-3">
                    <div class="card-body" style="color: black!important;">
                        <h5 class="card-title">Existen cuotas pendientes</h5>
                        <p class="card-text">Verifique las cuotas pendientes para aprobarlas o rechazarlas.</p>
                        <a href="{{ url_for('pagos.index_pendings') }}" class="btn btn-dark">Ver cuotas pendientes</a>
                    </div>
                </div>
            {% endif %}
            {% if has_permission("payments_show") %}
                {% block header_title %}<h1 class="text-center fw-semibold mb-4">Cuotas del mes</h1>{% endblock %}
                <form action="{{ url_for('pagos.search') }}" method="POST">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                    <div class="d-grid gap-2 gap-md-4 d-md-flex justify-content-md-center py-2">
                        <div class="input-group mb-3">
                            <input name="input" type="text" class="form-control" placeholder="Número o apellido del socio" aria-label="Número o apellido del socio" aria-describedby="basic-addon2" required>
                            <button type="submit" class="btn btn-dark">Confirmar</a>
                        </div>
                    </div>
                </form>
            {% endif %}
            {% if exists %}
                <div class="table table-dark">
                    <table class="">
                        <thead>
                            <tr>
                                <th>Socio</th>
                                <th>Monto</th>
                                <th>Estado</th>
                                <th>Mes a abonar</th>
                                <th>Opciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for cuota in pages.items %} 
                                <tr>
                                    <td>{{cuota.nombre}} {{cuota.apellido}}</td>
                                    <td>{{cuota.monto}}</td>
                                    <td>{{cuota.estado}}</td>
                                    <td>{{cuota.created_at|datetime_format('%m-%Y')}}</td>
                                    <!--Más info-->
                                    <td>
                                        <div class="d-grid gap-2 d-md-flex justify-content-lg-center justify-content-start mt-auto">
                                            {% if has_permission("payments_show") %}
                                                <a class="btn btn-sm btn-inscribir" href="{{ url_for('pagos.show_info_cuota', id_cuota = cuota.id) }}">
                                                    {% if cuota.estado == 'Impaga' %}
                                                        Más info
                                                    {% else %}
                                                        Comprobante
                                                    {% endif %}
                                                </a>
                                            {% endif %}

                                            {% if has_permission("payments_import") %}
                                                <!-- Button trigger modal -->
                                                {% if cuota.estado == 'Impaga' %}
                                                    <button type="button" class="btn btn-sm btn-especial" data-bs-toggle="modal" data-bs-target="#staticBackdrop--{{ cuota.id }}">
                                                        Pagar
                                                    </button>
                                                {% endif %}
                                            {% endif %}
                                        </div>
                                        
                                        <!-- Modal -->
                                        <div class="modal fade" id="staticBackdrop--{{ cuota.id }}" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1">
                                            <div class="modal-dialog">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h1 class="modal-title fs-5">Confirmación de pago</h1>
                                                    </div>
                                                    <div class="modal-body"> 
                                                        <p>¿Está segur@ que desea efectuar el pago?</p>
                                                    </div>
                                                
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                                                        <a href="{{ url_for('pagos.pagar_cuota', id_cuota = cuota.id) }}">
                                                            <button type="button" class="btn btn-primary">Confirmar</button>
                                                        </a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% else %}
                <h1>NO HAY CUOTAS EN EL MES</h1>
            {% endif %}
        </div>        
    {% endblock %}
    {% block buttons %}
        <div class="d-grid gap-4 d-md-flex justify-content-md-between mt-auto pt-4 pb-2">
            {% include "paginacion.html" %}
        </div>
        {% block button_bottom %}
            {% if has_permission("payments_import") %}
                <div class="d-grid gap-2 d-md-flex justify-content-md-center mt-auto pt-2 pb-2">
                    <a href="{{ url_for('pagos.create_cuotas') }}" class="btn btn-dark">Generar las cuotas de este mes</a> 
                </div>
            {% endif %}
        {% endblock %}
    {% endblock %}
{% endif %}

admin/src/web/templates/cuotas/show_comprobante.html
{% extends "base.html" %}
{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/comprobante.css') }}">
{% endblock %}

{% set active_page = "pagos" %}
{% if has_permission("payments_show") %}
    {% block title %}Comprobante de pago{% endblock %}

    {% block content %}
        <div class="container-fluid py-5">
            <h1 class="text-center fw-semibold mb-5">Comprobante de pago</h1>
            <div class="col d-flex justify-content-center">
                <div class="card mb-3"> 
                    <div class="row g-0">
                      <div class="col-md-4 mx-auto d-flex align-items-center">
                          <div class="container">
                            <div class="row row-cols-2">
                                <div class="col-12 pb-4">
                                    <img src="{{ url_for('static', filename='/images/logo.png') }}" class="img-fluid rounded-start" alt="Logo del club">
                                </div>
                                {% if comprobante.recibo_txt %}
                                <div class="col-12 text-center">
                                    <span class="fw-semibold fst-italic">"{{comprobante.recibo_txt}}"</span>
                                </div>
                                {% endif %}
                            </div>
                          </div>
                      </div>
                      <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title fw-semibold pb-2">Número de cuota: #{{comprobante.id}}</h5>
                            <p class="card-text">Socio: {{comprobante.nombre}}</p> 
                            <p class="card-text">Nro. de socio: {{ comprobante.socio }}</p>
                            <p class="card-text">Fecha de creación: {{ comprobante.fecha_creacion }}</p>
                            {% if comprobante.fecha_pago|length %}
                                <p class="card-text">Fecha de pago: {{ comprobante.fecha_pago}}</p>
                            {% else %}
                                <p class="card-text">Estado: impaga</p>
                            {% endif %}
                            <p class="card-text">La cuota cubre los siguientes gastos:</p>
                                <table class="table" style="margin-right: 0px;">
                                    <thead>
                                        <tr>
                                            <th>Motivo</th>
                                            <th>Costo</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>Valor de cuota base</td>
                                            <td>{{ comprobante.detalle.base }}</td>
                                        </tr>
                                        <tr>
                                            {% if comprobante.detalle.recargo != 0 %}
                                                <td>Recargo por deudas</td>
                                                <td>{{ comprobante.detalle.recargo }}</td>
                                            {% endif %}
                                        </tr>
                                        {% for key, value in comprobante.detalle.disciplinas.items() %}
                                            <tr>
                                                <td>{{ key }}</td>
                                                <td>{{ value}}</td>
                                            </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            <hr>
                            <p class="card-text fw-semibold">Monto total: ${{ comprobante.monto}}</p>
                            <div class="card-footer text-muted">Última modificación: {{ comprobante.fecha_mod}}</div>
                        </div>
                    </div>
                  </div>
              </div>
          </div>
            <div class="d-grid gap-2 d-md-flex justify-content-md-center mt-auto py-4">
                <a class="btn btn-dark" href="{{ url_for('pagos.download') }}">Descargar</a>
                <a class="btn btn-dark" href="{{ url_for('pagos.searcher') }}">Volver al listado de cuotas</a>
            </div>
        </div>
    {% endblock %}
{% endif %}